config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :posts
  end

  namespace :public do
    
  end

  root to: 'public/home#show'

end

app/models/post.rb
class Post < ActiveRecord::Base
  #associations
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  #macros
  has_secure_password
  has_one :user_settings, dependent: :destroy

  accepts_nested_attributes_for :user_settings

  #validations
  validates :email, uniqueness: true, presence: true


  def test
    'wee'
  end

  def settings
    self.user_settings
  end
end

app/models/user_settings.rb
class UserSettings < ActiveRecord::Base
  belongs_to :user, dependent: :destroy

  def test
    'woo'
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.all
  end

  def show
    redirect_to action: :edit
  end

  def edit
    @post = Post.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/edit.html.erb
<%= @post.inspect %>

app/views/admin/posts/index.html.erb
<% title 'Edit Posts' %>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th></th>
  </tr>
<% @posts.each do |post| %>
  <tr>
      <td><%= post.title %></td>
      <td>By <%= post.user.settings.first_name %></td>
      <td><%= link_to 'Edit', edit_admin_post_path(post.id) %></td>
  </tr>
<% end %>
</table>

app/views/admin/posts/show.html.erb
show.html.erb

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags :site => 'Blog.com', :reverse => true %>
</head>
<body>
  <h1>Blog Administration</h1>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags :site => 'Blog.com', :reverse => true %>
</head>
<body>
  <%= yield %>
</body>
</html>